allowRepeatingEvents: true
color: '#9E31C4'
description: 'The default calendar'
descriptionFieldHandle: null
fieldLayout: null
handle: default
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: null
name: Default
siteSettings:
  815c4fd2-6502-4d25-8605-4d74668e8b0d:
    enabledByDefault: true
    hasUrls: false
    siteId: ec473f07-152f-423b-90df-ac425e6068a1 # Spanish
    template: null
    uriFormat: null
  aae92448-744c-47d9-9847-843c19e64d1b:
    enabledByDefault: true
    hasUrls: false
    siteId: 5da841b1-ca0d-46ff-8bb1-04d6c889ac54 # English
    template: null
    uriFormat: null
titleFormat: null
titleLabel: Title
