fieldLayouts:
  3079b909-ff31-4f40-98a0-10c57767ab1f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb20e317-f44b-475c-811e-eceacd1e4f36
            warning: null
            width: 100
          -
            fieldUid: 21903cb2-5b82-49ea-9766-e120d0951ea3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce40d913-bd6d-44ce-a519-ec8a635072b4
            warning: null
            width: 100
          -
            fieldUid: abcda4a4-b1db-4677-b5d6-69588443704f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b72a271-858c-483b-ba95-4180d6a8c0d3
            warning: null
            width: 100
          -
            fieldUid: 4a0cb371-14a6-415d-84db-fc0512410ec8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb4bdae4-cb23-400d-bb7a-ecf0e27b472d
            warning: null
            width: 100
        name: Content
        uid: 7a2f45b6-e137-45fc-885e-f9488e64c590
handle: homepage
hasTitleField: false
name: Homepage
section: 54e60257-f31a-44aa-960e-bbd364197e28
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
