fieldLayouts:
  e73b4186-2fad-4c0f-8eae-bbb884932c58:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 11f501c2-3372-41e5-994a-f9e45f0fcbd3
            warning: null
            width: 100
        name: Content
        uid: 0af1ca00-8065-45e9-b3b6-fffc67b9a1a7
fs: site
handle: site
name: Site
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: site
