fieldLayouts:
  e1ad1c2a-97c8-4b64-9d59-41e897a98298:
    tabs:
      -
        elements:
          -
            fieldUid: 21903cb2-5b82-49ea-9766-e120d0951ea3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f088d1ae-0e27-4b44-8409-9b280767bc95
            warning: null
            width: 100
          -
            fieldUid: abcda4a4-b1db-4677-b5d6-69588443704f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa115fb5-c963-4b33-ae24-6142e5fbea98
            warning: null
            width: 100
        name: Default
        uid: 3a845609-01dd-4d7f-bafd-8c001c4be32d
handle: globals
name: Globals
sortOrder: 0
