columnSuffix: null
contentColumnType: string
fieldGroup: 94b4d5ac-d7ea-4241-a6cb-92b39f482f99 # Common
handle: longform
instructions: ''
name: Longform
searchable: false
settings:
  errorMessage: 'Unable to find component class ''verbb\vizy\fields\VizyField''.'
  expectedType: verbb\vizy\fields\VizyField
  settings: '{"availableTransforms":"*","availableVolumes":"*","columnType":"text","configSelectionMode":"choose","defaultTransform":"","fieldData":[{"id":"group-9u4U9ASooD","name":"Default","blockTypes":[{"id":"type-IXfgwp16KQ","name":"Text","handle":"text","icon":{"label":"HireAHelper","value":"hire-a-helper-brands"},"enabled":true,"layoutUid":"b262e1c1-d257-4432-94ba-dc5c168284bc"}]}],"manualConfig":"","showUnpermittedFiles":false,"showUnpermittedVolumes":false,"vizyConfig":""}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
