columnSuffix: null
contentColumnType: string
fieldGroup: 94b4d5ac-d7ea-4241-a6cb-92b39f482f99
handle: seo
instructions: ''
name: SEO
searchable: false
settings:
  errorMessage: 'Component class ''nystudio107\seomatic\fields\SeoSettings'' belongs to an uninstalled plugin (SEOmatic).'
  expectedType: nystudio107\seomatic\fields\SeoSettings
  settings: '{"elementDisplayPreviewType":"google","facebookTabEnabled":"","generalEnabledFields":["seoTitle","seoDescription","seoImage"],"generalTabEnabled":"1","sitemapTabEnabled":"","twitterTabEnabled":""}'
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
